title: Anton Dambrouski
email: Anton.Dambrouski@gmail.com
description: >-
  First steps in creating my own site by using github pages.
  At the beginning of this journey I want to create something simple and then increase functionality of this site.
  I am going to change description step by step as I'll improve this site.
baseurl: ""
url: "https://antondambrouski.github.io/"
markdown: kramdown
github_username: AntonDambrouski

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
